Models/Booking.cs
using System.ComponentModel.DataAnnotations;

namespace BookStore.Models
{
    public class Booking
    {
        public int Id { get; set; }

        public string Delivery_Adress { get; set; }

        public DateTime Delivery_date { get; set; }

        public DateTime Delivery_Time { get; set; }

        public int? UserId { get; set; }

        public User? User { get; set; }

        public int StatusId { get; set; }

        public Status Status { get; set; }

        public int ProductId { get; set; }

        public Product Product { get; set; }
    }
}

Controllers/BookingController.cs
namespace BookStore.Controllers
{
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using BookStore.Models;
using AutoMapper;
using BookStore.Interfaces;
using BookStore.DTO;
using BookStore.Enums;

    public class BookingController : Controller
    {
        private readonly IBookingService _bookingService;

        private readonly IMapper _mapper;

        public BookingController(IBookingService bookingService, IMapper mapper)
        {
            _bookingService = bookingService;
            _mapper = mapper;
        }


        // GET: Booking
        public IActionResult Index(string searchString)
        {
            if (_bookingService.Get() == null)
            {
                return Problem("Booking list is empty.");
            }

            var bookings = from b in _bookingService.Bookings()
                           select b;

            if (!String.IsNullOrEmpty(searchString))
            {
                bookings = bookings.Where(b => b.Product!.Name.Contains(searchString));
            }
            return View(bookings.ToList());
        }

        // GET: Booking/Details/5
        public IActionResult Details(int id)
        {
            if (id == null || _bookingService.Get(id) == null)
            {
                return NotFound();
            }

            var booking = _bookingService.Get(id);

            return View(booking);
        }

        // GET: Booking/Create
        public IActionResult Create(int id)
        {
            ViewData["Product"] = _bookingService.GetProducts().Where(p => p.Id == id).Select(p => p.Name).FirstOrDefault();
            ViewData["Price"] = _bookingService.GetProducts().Where(p => p.Id == id).Select(p => p.Price).FirstOrDefault();
            return View();
        }

        // POST: Booking/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(string Product, [Bind("Delivery_Adress,Delivery_date,Delivery_Time")] BookingDto booking)
        {
            booking.ProductId = _bookingService.GetProducts().Where(p => p.Name == Product).FirstOrDefault().Id;
            booking.StatusId = (int)Statuses.SUBMITED;
            if (ModelState.IsValid)
            {
                var bookingMap = _mapper.Map<Booking>(booking);
                bookingMap.Status = _bookingService.GetStatuses().Where(s => s.Id == (int)Statuses.SUBMITED).FirstOrDefault();
                bookingMap.Product = _bookingService.GetProducts().Where(p => p.Name == Product).FirstOrDefault();
                bookingMap.Product.Bookings.Add(bookingMap);
                if (!_bookingService.Post(bookingMap))
                {
                    ModelState.AddModelError("", "Something went wrong, booking was not saved");
                    return StatusCode(500, ModelState);
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["Product"] = _bookingService.GetProducts().Where(p => p.Id == booking.ProductId).Select(p => p.Name).FirstOrDefault();
            ViewData["Price"] = _bookingService.GetProducts().Where(p => p.Id == booking.ProductId).Select(p => p.Price).FirstOrDefault();
            return View(booking);
        }

        // GET: Booking/Edit/5
        public IActionResult Edit(int id)
        {
            var booking = _bookingService.Get(id);
            if (id == null || booking == null)
            {
                return NotFound();
            }
            ViewData["ProductId"] = new SelectList(_bookingService.GetProducts(), "Id", "Id", booking.ProductId);
            ViewData["StatusId"] = new SelectList(_bookingService.GetStatuses(), "Id", "Id", booking.StatusId);
            ViewData["UserId"] = new SelectList(_bookingService.GetUsers(), "Id", "Id", booking.UserId);
            return View(booking);
        }

        // POST: Booking/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Delivery_Adress,Delivery_date,Delivery_Time,UserId,StatusId,ProductId")] BookingDto bookingUpdate)
        {
            if (ModelState.IsValid)
            {
                if (bookingUpdate == null)
                    return BadRequest(ModelState);

                if (id != bookingUpdate.Id)
                    return BadRequest(ModelState);

                if (!_bookingService.Exists(id))
                    return NotFound();

                if (!ModelState.IsValid)
                    return BadRequest(ModelState);

                var bookingMap = _mapper.Map<Booking>(bookingUpdate);

                if (!_bookingService.Put(bookingMap))
                {
                    ModelState.AddModelError("", "Something went wrong while updating booking");
                    return StatusCode(500, ModelState);
                }
                return RedirectToAction(nameof(Index));
            }
            var booking = _bookingService.Get(id);
            ViewData["ProductId"] = new SelectList(_bookingService.GetProducts(), "Id", "Id", booking.ProductId);
            ViewData["StatusId"] = new SelectList(_bookingService.GetStatuses(), "Id", "Id", booking.StatusId);
            ViewData["UserId"] = new SelectList(_bookingService.GetUsers(), "Id", "Id", booking.UserId); ;
            return View(booking);
        }

        //add comment
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateApprovedStatus(string id)
        {
            var Id = Convert.ToInt16(Request.Form["id"]);
            var booking = _bookingService.Get(Id);
            booking.StatusId = (int)Statuses.APPROVED;

                if (!_bookingService.Put(booking))
                {
                    ModelState.AddModelError("", "Something went wrong while updating booking");
                    return StatusCode(500, ModelState);
                }

            return RedirectToAction(nameof(Index)); 
        }

        // POST: Booking/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateRejectStatus(string id)
        {
            var Id = Convert.ToInt16(Request.Form["id"]);
            var booking = _bookingService.Get(Id);
            booking.StatusId = (int)Statuses.REJECTED;

            if (!_bookingService.Put(booking))
            {
                ModelState.AddModelError("", "Something went wrong while updating booking");
                return StatusCode(500, ModelState);
            }

            return RedirectToAction(nameof(Index));
        }

        // POST: Booking/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateCompleteStatus(string id)
        {
            var Id = Convert.ToInt16(Request.Form["id"]);
            var booking = _bookingService.Get(Id);
            booking.StatusId = (int)Statuses.COMPLETED;

            if (!_bookingService.Put(booking))
            {
                ModelState.AddModelError("", "Something went wrong while updating booking");
                return StatusCode(500, ModelState);
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Booking/Delete/5
        public IActionResult Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = _bookingService.Get(id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        // POST: Booking/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var bookingToDelete = _bookingService.Get(id);

            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            if (!_bookingService.Delete(bookingToDelete))
            {
                ModelState.AddModelError("", "Something went wrong while deleting booking");
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/BookingsController.cs
namespace BookStore.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using BookStore.Interfaces;
    using BookStore.DTO;
    using AutoMapper;
    using BookStore.Models;

    [Route("api/[controller]")]
    [ApiController]
    public class BookingsController : ControllerBase
    {
        private readonly IBookingService _bookingService;

        private readonly IMapper _mapper;

        public BookingsController(IBookingService bookingService, IMapper mapper)
        {
            _bookingService = bookingService;
            _mapper = mapper;
        }

        // GET: api/Bookings
        [HttpGet]
        [ProducesResponseType(200, Type = typeof(IEnumerable<Booking>))]
        public IActionResult GetBookings()
        {
            var result = _mapper.Map<List<BookingDto>>(_bookingService.Get());

            if (!ModelState.IsValid)
                return BadRequest();

            return StatusCode(200, result);
        }

        // GET: api/Bookings/5
        [HttpGet("{id}")]
        [ProducesResponseType(400)]
        [ProducesResponseType(200, Type = typeof(Booking))]
        public IActionResult GetBooking(int id)
        {
            if (!_bookingService.Exists(id))
                return NotFound();

            var booking = _mapper.Map<BookingDto>(_bookingService.Get(id));

            if (!ModelState.IsValid)
                return BadRequest();

            return StatusCode(200, booking);
        }

        // PUT: api/Bookings/5
        [HttpPut("{id}")]
        [ProducesResponseType(400)]
        [ProducesResponseType(404)]
        [ProducesResponseType(204)]
        public IActionResult PutBooking(int id, BookingDto updatedBooking)
        {
            if (updatedBooking == null)
                return BadRequest(ModelState);

            if (id != updatedBooking.Id)
                return BadRequest(ModelState);

            if (!_bookingService.Exists(id))
                return NotFound();

            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            var bookingMap = _mapper.Map<Booking>(updatedBooking);

            if (!_bookingService.Put(bookingMap))
            {
                ModelState.AddModelError("", "Something went wrong while updating booking");
                return StatusCode(500, ModelState);
            }
            return StatusCode(204, "Booking was updated");
        }

        // POST: api/Bookings
        [HttpPost]
        [ProducesResponseType(201)]
        [ProducesResponseType(400)]
        public IActionResult PostBooking(BookingDto createBooking)
        {
            if (createBooking == null)
                return BadRequest(ModelState);

            var booking = _mapper.Map<List<BookingDto>>(_bookingService.Get())
                .Where(b => b.Delivery_Adress == createBooking.Delivery_Adress 
                && b.ProductId == createBooking.ProductId
                && b.StatusId == createBooking.StatusId
                && b.UserId == createBooking.UserId
                && b.Delivery_date == createBooking.Delivery_date).FirstOrDefault();

            if (booking != null)
            {
                ModelState.AddModelError("", "Booking already exists");
                return StatusCode(422, ModelState);
            }

            var bookingMap = _mapper.Map<Booking>(createBooking);
            if (!_bookingService.Post(bookingMap))
            {
                ModelState.AddModelError("", "Something went wrong, booking was not saved");
                return StatusCode(500, ModelState);
            }
            return StatusCode(201, "Booking was created");
        }

        // DELETE: api/Bookings/5
        [HttpDelete("{id}")]
        [ProducesResponseType(204)]
        [ProducesResponseType(400)]
        [ProducesResponseType(404)]
        public IActionResult DeleteBooking(int id)
        {
            if (!_bookingService.Exists(id))
                return NotFound();

            var bookingToDelete = _bookingService.Get(id);

            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            if (!_bookingService.Delete(bookingToDelete))
            {
                ModelState.AddModelError("", "Something went wrong while deleting booking");
            }

            return StatusCode(204, "Booking was deleted");
        }

    }
}

Views/Booking/Create.cshtml
@model BookStore.Models.Booking

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Booking</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Delivery_Adress" class="control-label"></label>
                <input asp-for="Delivery_Adress" class="form-control" />
                <span asp-validation-for="Delivery_Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Delivery_date" class="control-label"></label>
                <input asp-for="Delivery_date" asp-format="{0:yyyy-MM-ddTHH:mm}" class="form-control" />
                <span asp-validation-for="Delivery_date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Delivery_Time" class="control-label"></label>
                <input asp-for="Delivery_Time"  class="form-control" />
                <span asp-validation-for="Delivery_Time" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product" class="control-label"></label>
                <input asp-for="Product" class="form-control" type="text" readonly value=@ViewData["Product"] />
            </div>
            <div class="form-group">
                <label asp-for="Product.Price" class="control-label"></label>
                <input asp-for="Product.Price" class="form-control" type="text" readonly value=@ViewData["Price"] />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Booking/Delete.cshtml
@model BookStore.Models.Booking

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Booking</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Delivery_Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Delivery_Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Delivery_date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Delivery_date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Delivery_Time)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Delivery_Time)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Booking/Details.cshtml
@model BookStore.Models.Booking

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Booking</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Delivery_Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Delivery_Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Delivery_date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Delivery_date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Delivery_Time)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Delivery_Time)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Booking/Edit.cshtml
@model BookStore.Models.Booking

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Booking</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Delivery_Adress" class="control-label"></label>
                <input asp-for="Delivery_Adress" class="form-control" />
                <span asp-validation-for="Delivery_Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Delivery_date" class="control-label"></label>
                <input asp-for="Delivery_date" class="form-control" />
                <span asp-validation-for="Delivery_date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Delivery_Time" class="control-label"></label>
                <input asp-for="Delivery_Time" class="form-control" />
                <span asp-validation-for="Delivery_Time" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StatusId" class="control-label"></label>
                <select asp-for="StatusId" class="form-control" asp-items="ViewBag.StatusId"></select>
                <span asp-validation-for="StatusId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <select asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId"></select>
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Booking/Index.cshtml
@model IEnumerable<BookStore.Models.Booking>

@{
    ViewData["Title"] = "Index";
}
<form asp-controller="Booking" asp-action="Index" method="get">
    <p>
        Title: <input type="text" name="searchString" />
        <input type="submit" value="Search" />
    </p>
</form>

<h1>Bookings</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-sm-4">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        @Html.DisplayNameFor(model => model.Product.Image_Path)
                        <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
                    </div>
                    <div class="panel-body">
                        <div> <b>@Html.DisplayFor(model => item.User.Name) </b> </div>
                        <div> <b>@Html.DisplayFor(model => item.Product.Name) </b> </div>
                        <div> <b>@Html.DisplayFor(model => item.Product.Price) </b> </div>
                        <div> <b>@Html.DisplayFor(model => item.Delivery_date.Date)</b></div>
                        <div> <b>@Html.DisplayFor(model => item.Delivery_Time.TimeOfDay)</b> </div>
                        <div> <b>@Html.DisplayFor(model => item.Delivery_Adress)</b> </div>
                        <div> <b>@Html.DisplayFor(model => item.Status.Name)</b> </div>
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-md-4">
                                <form  asp-controller="Booking" asp-action="UpdateApprovedStatus" method="post">
                                        <input type="hidden" value="@item.Id" name="id" />
                                        <input  class="btn btn-success" type="submit" value="Approve" />
                                </form>
                            </div>
                            <div class="col-md-4">
                                <form asp-controller="Booking" asp-action="UpdateRejectStatus" method="post">
                                        <input type="hidden" value="@item.Id" name="id" />
                                        <input class="btn btn-danger" type="submit" value="Reject" />
                                </form>
                            </div>
                            <div class="col-md-4">
                                <form asp-controller="Booking" asp-action="UpdateCompleteStatus" method="post">
                                        <input type="hidden" value="@item.Id" name="id" />
                                        <input class="btn btn-info" type="submit" value="Complete" />
                                </form>
                              </div>
                        </div>
                        <div class="center-block">
                                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                       </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>